
---
framework: mocha
preRun:
     command:
        - npm ci
        - npm run build
preMerge:
  pattern:
    - "test/*-test.js"
postMerge:
  pattern: 
    - "test/*-test.js"
postRun:
     command:
        - node --version
# configFile: mocharc.yml
version: 1.0